### ISSUE TITLE
Question regarding the need to transfer asset to contract first

### ISSUE THREAD

**Issue by suahnkim** [tokamak-network/multisender_shivansh#11]
As far as I understood the code, the contract first receives the asset and transfers 
This means, number of transfers required is always +1 of number of recipients 

But if you think about it, we can use safe transfer to transfer the funds directly to the recipients. (Would reduce number of transfers by 1)

My question:
What are the pros of transferring the asset to the contract first, when compared to transferring directly?

**Comment by usgeeus** [comment]
I suggest compare the gasUsage of
1 transferFrom + n transfers **vs** n transferFroms

**Comment by Shivansh070707** [comment]
gasUsed: 331586n,transferFrom then transfer
 gasUsed: 348503n, - transferFrom in loop

**Comment by usgeeus** [comment]
Never mind my coment, transferfroms need approvals for each destination before the tx

**Comment by suahnkim** [comment]
issue is resolved

**Comment by suahnkim** [comment]
@usgeeus don't we need to approve just this contract and use transferfrom? 
in that case, I don't understand why we need multiple approvals? and why transferring the assets to the contract first will have lower gas usage.

**Comment by usgeeus** [comment]
Ah yes, that's right. I was wrong. We only need to approve just this contract and use transferfrom

**I haven't tested it myself,** but transfer is cheaper than TransferFrom, because it has one less parameter( from). 
extra calldata cost of transferFrom (+ address from) : 16 * 20 + 4 * 12 = 368
I think this could be the reason
The cost difference may not be much when transferFrom executed once, but when transferFrom executed multiple times through a loop, the difference may be a bit more.

**Comment by suahnkim** [comment]
ah that makes sense. closing the issue
