### ISSUE TITLE
Gas Limit Issue on `multisendETH`

### ISSUE THREAD

**Issue by ghost** [tokamak-network/multisender_shivansh#8]
**Describe the bug**
`multisendETH` may run out of gas if the arrays are too large.
**Configuration**
- Severity: medium

**Impact**

 
**Recommendation**
We should Implement batch processing or limit the size of input arrays to ensure that transactions do not exceed gas limits.
This approach breaks down the list of addresses into manageable chunks, reducing the risk of running out of gas.

**Exploit Scenario**

**Demo**

```

**Comment by Shivansh070707** [comment]
I think we can add this check from frontend side , because we are sending a bunch of transfers , if we restrict to n number of transfer then it wont be feasible

**Comment by suahnkim** [comment]
@0x6e616d, Shivansh is correct, this is the way it has been done in other similar dapps. If you are ok with closing the issue, please leave a reply. 

@Shivansh070707, Zena (@Zena-park) reopened this issue because we created this rule that **only the person who raised the issue can close the issue**. 

However, we found an issue that the person who raised the issue cannot close the issue due to access control issue. We will discuss it today and let you know how we will change this part. Sorry for the confusion

**Comment by ghost** [comment]
> @0x6e616d, Shivansh is correct, this is the way it has been done in other similar dapps. If you are ok with closing the issue, please leave a reply.
> 
> @Shivansh070707, Zena (@Zena-park) reopened this issue because we created this rule that **only the person who raised the issue can close the issue**.
> 
> However, we found an issue that the person who raised the issue cannot close the issue due to access control issue. We will discuss it today and let you know how we will change this part. Sorry for the confusion

Okay, I will close this
